anodot/daria

agent/src/agent/constants.py, agent/src/agent/source/schemaless.py, agent/src/agent/source/tcp.py, agent/src/agent/streamsets_api_client.py, agent/tests/test_pipelines/test_tcp_http.py
rename grok pattern definitions file to custom grok patterns file in source cli
remove test tcp server
increase preview timeout
=> Splunk cli fixes

.pre-commit-config.yaml, .style.yapf, Makefile, README.md
Added style and config files for pre-commit hook.
How to use could be seen in [Jira task #AL-10019](https://anodot.atlassian.net/browse/AL-10019)
=> Added style and config files for pre-commit hook

agent/requirements.txt, agent/src/agent/api/main.py, agent/src/agent/modules/wtforms_json.py, agent/src/agent/pipeline/config/jython_scripts/sage.py, streamsets/Dockerfile
=> [sage] - add Source header

agent/src/agent/api/docs/routes/pipelines.md, agent/src/agent/api/docs/routes/sources.md, agent/src/agent/api/routes/source.py, agent/tests/api/source/test_directory.py, agent/tests/api/source/test_influx.py
- Added sources/<source_id> endpoint to GET source config
- Added few tests
- Updated API docs
Related ticket: [AL-10556](https://anodot.atlassian.net/browse/AL-10556)
=> [agent][api] API endpoint for getting a single source configs

agent/src/agent/data_extractor/observium/observium.py, agent/src/agent/modules/field.py, agent/tests/input_files/observium/pipelines.json, agent/tests/test_pipelines/expected_output/observium_storage_transform.json, volumes/mysql-initdb/observium.sql
- Skip `None` measurements
- Update tests
Related ticket: [AL-10834](https://anodot.atlassian.net/browse/AL-10834)
=> [agent][observium] Skip measurements with None value

agent/src/agent/pipeline/manager.py, agent/tests/unit/test_supports_schema.py
Related ticket: [AL-10969](https://anodot.atlassian.net/browse/AL-10969)
=> [agent][mssql] Fix supports_schema for Microsoft SQL

Makefile, agent/src/agent/pipeline/config/jython_scripts/promql.py, agent/src/agent/pipeline/config/stages/source/promql.py, agent/tests/input_files/promql/pipelines.json, agent/tests/test_pipelines/test_promql_http.py
- Send `last_timestamp` as watermark if no data and `DVP_ENABLED`
Related ticket: [AL-11040](https://anodot.atlassian.net/browse/AL-11040)
=> [agent][victoria] Add DVP config support

Makefile, agent/src/agent/api/routes/pipeline.py, agent/src/agent/monitoring/metrics.py, agent/tests/input_files/monitoring/pipelines.json, agent/tests/input_files/monitoring/sources.json, agent/tests/test_monitoring.py
- Added new metric - avg pipeline lag
Related ticket: [AL-10971](https://anodot.atlassian.net/browse/AL-10971)
=> [agent][monitoring] Add new metric - avg pipeline lag

agent/src/agent/pipeline/config/validators.py, agent/src/agent/pipeline/jdbc/query.py, agent/src/agent/pipeline/validators/jdbc_query.py, agent/tests/input_files/jdbc/pipelines.json, agent/tests/test_pipelines/test_mysql_http.py
- Use indexed field for SQL Server query
Related ticket: [AL-11317](https://anodot.atlassian.net/browse/AL-11317)
=> [AL-11317] Refactored SQL Server query

agent/src/agent/pipeline/manager.py, agent/src/agent/scripts/reset_retry_counters.py
- Set retries.last_updated to datetime.now() if it's None
Related ticket: [AL-11381](https://anodot.atlassian.net/browse/AL-11381)
=> [agent][script] Fix retry counter reset script

agent/src/agent/destination/manager.py
https://anodot.atlassian.net/browse/AL-10210
Delete trailing slashes in destination manager
=> Delete trailing slashes in destination url

agent/src/agent/api/routes/pipeline.py, agent/src/agent/pipeline/__init__.py, agent/src/agent/pipeline/exception.py, agent/src/agent/pipeline/manager.py
https://anodot.atlassian.net/browse/AL-11339
=> Fix conflict if pipeline is running

agent/src/agent/pipeline/config/jython_scripts/solarwinds.py, containers/dummy_destination/main.py
- Removed 'Z' at the end of formatted date, like `2021-03-30T00:00:00Z` -> `2021-03-30T00:00:00`
- Add batch processing in case it reaches batchSize limit
Related ticket: [AL-11625](https://anodot.atlassian.net/browse/AL-11625)
=> [agent][solarwinds] Fix date format in solarwinds query

agent/src/agent/data_extractor/snmp/snmp.py, agent/src/agent/source/json_schema_definitions/snmp.json, agent/src/agent/source/source.py, agent/src/agent/source/validator.py, agent/tests/input_files/snmp_sources.json
- SNMP protocol version added to config (v1 and v2c possible values)
- Fixed multiple hosts validation. If all of the hosts are unavailable - Validation exception raised
- Refactored data extraction for the pipeline. If host becomes unavailable, no exception
Related tickets: [AL-11654](https://anodot.atlassian.net/browse/AL-11654),  [AL-11655](https://anodot.atlassian.net/browse/AL-11655)
=> [agent][snmp] Source bug fixes

agent/src/agent/pipeline/config/jython_scripts/prtg.py, agent/src/agent/pipeline/json_builder/prtg.py, agent/tests/input_files/prtg/pipelines.json, agent/tests/input_files/prtg/sources.json, agent/tests/test_pipelines/test_2/test_cacti.py, agent/tests/test_pipelines/test_2/test_rrd.py, agent/tests/test_pipelines/test_zpipeline_base.py
- No need to specify timestamp in pipeline config
- Always compute watermark with timezone (default is UTC)
=> [agent][prtg] Fix default timestamp

scripts/agent.sh, scripts/docker-compose.yml
- Fix set-thread-pool-size and set-heap-size commands
- Set default SDC_JAVA_OPTS as power of 2
=> [agent] Script agent.sg update

agent/src/agent/pipeline/config/jython_scripts/convert_to_metrics_30.py, agent/tests/input_files/directory/pipelines.json, agent/tests/test_pipelines/expected_output/directory_tags.json
- Fixed tags conversion
- Updated related tests
=> [agent][tags] Fix dynamic tags for directory

agent/requirements.txt, agent/src/agent/data_extractor/snmp/snmp.py, agent/src/agent/pipeline/json_builder/json_schema_definitions/snmp.json, agent/src/agent/pipeline/json_builder/snmp.py, agent/tests/input_files/snmp_pipelines.json, agent/tests/test_pipelines/expected_output/snmp_table.json, agent/tests/test_pipelines/test_2/test_snmp.py
- Added possibility to extract metrics from SNMP tables
- Tests with data from table
=> [agent][snmp] Extract metrics from SNMP tables

agent/src/agent/destination/destination.py
Related ticket: [AL-11927](https://anodot.atlassian.net/browse/AL-11927)
=> [agent][destination] Update check expiration logic for auth_token

agent/src/agent/data_extractor/snmp/snmp.py
What this fix does:
If `use_indexes` option is used, then SNMP data requested by getCmd (instead of nextCmd). Thus SNMP OIDs extracted as follows:
```python
[
'1.3.6.1.2.1.2.2.1.3.1',
'1.3.6.1.2.1.2.2.1.3.2',
'1.3.6.1.2.1.2.2.1.2.1',
'1.3.6.1.2.1.2.2.1.2.2',
'1.3.6.1.2.1.2.2.1.4.1',
'1.3.6.1.2.1.2.2.1.4.2',
'1.3.6.1.2.1.2.2.1.5.1',
'1.3.6.1.2.1.2.2.1.5.2',
]
```
and a new function sorts this list by last digit, e.g. index inside table, and groups result to this:
```python
[['1.3.6.1.2.1.2.2.1.3.1',
'1.3.6.1.2.1.2.2.1.2.1',
'1.3.6.1.2.1.2.2.1.4.1',
'1.3.6.1.2.1.2.2.1.5.1'],
['1.3.6.1.2.1.2.2.1.3.2',
'1.3.6.1.2.1.2.2.1.2.2',
'1.3.6.1.2.1.2.2.1.4.2',
'1.3.6.1.2.1.2.2.1.5.2']]
```
The grouping is needed because each group represents metrics for a single output record. The nextCmd command …
=> [agent][snmp] Add grouping in use_indexes case

agent/src/agent/pipeline/config/jython_scripts/snmp.py
Incorrect offset calculation caused sending 2 data points within one time interval
=> [agent][snmp] Fix incorrect offset

agent/tests/test_pipelines/test_2/test_mysql_http.py, docker-compose-dev.yml, docker-compose.yml
- Replace deleted from docker hub squid container
- Fix tests related to the watermark in local timezone
=> [hotfix] Replace deleted from docker hub squid container

agent/src/agent/data_extractor/snmp/snmp.py, agent/src/agent/pipeline/config/jython_scripts/snmp.py, agent/src/agent/pipeline/config/jython_scripts/snmp_raw.py, agent/src/agent/pipeline/config/stages/source/snmp.py, agent/src/agent/source/source.py, agent/tests/input_files/raw/sources/snmp.json, agent/tests/input_files/snmp/sources.json
- Use only the current offset value
- Separate snmp_query for SNMP Get command and query_timeout for request timeout to data_extractor
=> [agent][snmp] Fix historical offset usage

agent/install_requirements.sh, docker-compose-dev.yml, docker-compose.yml, scripts/docker-compose.yml
Related ticket: [AL-12143](https://anodot.atlassian.net/browse/AL-12143)
=> [agent][install] Synchronize PostgresSQL versions in dev/release compose files

agent/src/agent/api/routes/destination.py, agent/src/agent/cli/__init__.py, agent/src/agent/cli/destination.py, agent/src/agent/destination/manager.py, agent/src/agent/pipeline/config/base_pipelines/cacti.json, agent/src/agent/pipeline/config/base_pipelines/directory_schema.json, agent/src/agent/pipeline/config/base_pipelines/elastic.json, agent/src/agent/pipeline/config/base_pipelines/elastic_schema.json, agent/src/agent/pipeline/config/base_pipelines/influx2_schema.json, agent/src/agent/pipeline/config/base_pipelines/influx_http.json, agent/src/agent/pipeline/config/base_pipelines/influx_schema.json, agent/src/agent/pipeline/config/base_pipelines/jdbc.json, agent/src/agent/pipeline/config/base_pipelines/jdbc_schema.json, agent/src/agent/pipeline/config/base_pipelines/kafka_http.json, agent/src/agent/pipeline/config/base_pipelines/kafka_http_schema.json, agent/src/agent/pipeline/config/base_pipelines/mongo_http.json, agent/src/agent/pipeline/config/base_pipelines/observium_schema.json, agent/src/agent/pipeline/config/base_pipelines/promql.json, agent/src/agent/pipeline/config/base_pipelines/promql_schema.json, agent/src/agent/pipeline/config/base_pipelines/prtg_schema.json, agent/src/agent/pipeline/config/base_pipelines/rrd.json, agent/src/agent/pipeline/config/base_pipelines/sage_http.json, agent/src/agent/pipeline/config/base_pipelines/sage_schema.json, agent/src/agent/pipeline/config/base_pipelines/snmp_schema.json, agent/src/agent/pipeline/config/base_pipelines/solarwinds.json, agent/src/agent/pipeline/config/base_pipelines/tcp_server_http.json, agent/src/agent/pipeline/config/base_pipelines/zabbix_http.json, agent/tests/input_files/destination.json, agent/tests/test_destination.py
increase default maxRequestCompletionSecs and maxSendResponseWait for destination
=> destination config

agent/src/agent/pipeline/config/jython_scripts/promql.py, agent/src/agent/pipeline/jdbc/query.py
=> MSSQL and Impala: fix timestamp condition
